dist: bionic
sudo: required
language: node_js
node_js:
  - "8.11.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git cmake ninja-build g++ python
  - git clone https://github.com/juj/emsdk
  - cd emsdk
  - ./emsdk update-tags
  - ./emsdk install sdk-1.37.36-64bit
  - ./emsdk activate sdk-1.37.36-64bit
  - ./emsdk install  binaryen-tag-1.37.36-64bit
  - ./emsdk activate binaryen-tag-1.37.36-64bit


